---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '11.14.6'
  use_vagrant_berkshelf_plugin: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list: ["recipe[martinisoft-postgresql]"]
  attributes: {}

- name: server
  run_list: ["recipe[martinisoft-postgresql::server]"]
  attributes: {}
