---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '11.14.6'
  client_rb:
    node_name: walle
  data_bags_path: "test/integration/data_bags"

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04

suites:
- name: default
  run_list: ["recipe[martinisoft-postgresql]"]
  attributes:
    openssh:
      server:
        port:
          - 22
          - 22022
    chef_client:
      config:
        chef_server_url: "http://127.0.0.1:8889"

- name: server
  run_list: ["recipe[martinisoft-postgresql::server]"]
  attributes:
    dev_mode: true
    openssh:
      server:
        port:
          - 22
          - 22022
    chef_client:
      config:
        chef_server_url: "http://127.0.0.1:8889"

